#   ____            __ _  _____                    _
#  / ___|_ __ __ _ / _| ||_   _|_      _____  __ _| | _____
# | |   | '__/ _` | |_| __|| | \ \ /\ / / _ \/ _` | |/ / __|
# | |___| | | (_| |  _| |_ | |  \ V  V /  __/ (_| |   <\__ \
#  \____|_|  \__,_|_|  \__||_|   \_/\_/ \___|\__,_|_|\_\___/
#


# Pokrocile upravy Minecraftu
hack-minecraft:

  # Povoleni extra stakovani itemu, ktere normalne nejsou stakovat! Pozor: Muze bugovat!
  stacking:
    enabled: false # Pokud je na true, seznam dole pujde stakovat
    list:
      - 'WATER_BUCKET'
      - 'LAVA_BUCKET'

# Upravy chovani serveru (pokud je true) ochrana je aktivni
disables-and-fixes:

  # Deaktivace pouzivani nametagu na ArmorStandy
  nametag-on-armorstand: false

  # Deaktivace vody, ktera nici wheat v farmach
  water-breaking-wheat: false

  # Deaktivace rustu a fyziky kaktusu
  cactus-growing: false

  # Kompletni deaktivace Pumpin, Cactus a Meloun farmy (funkcnost)
  piston-eject-blocks: false

# Tweaks pro chat
chat:

  # Pokud je na true, tak hraci nebudou moct napsat jine znaky krome 0-9,A-Z
  block-unicode: true

### CONSOLE HIDER ###
#
#    hide-message:
#    - 'WARNING: unlocalizedName'
#
# Skryje vsechny zprav v konzoli, ktere obsahuji zadany text.

console:
  hide-message:
    - 'Kek: warning'

