#   ____            __ _  _____                    _
#  / ___|_ __ __ _ / _| ||_   _|_      _____  __ _| | _____
# | |   | '__/ _` | |_| __|| | \ \ /\ / / _ \/ _` | |/ / __|
# | |___| | | (_| |  _| |_ | |  \ V  V /  __/ (_| |   <\__ \
#  \____|_|  \__,_|_|  \__||_|   \_/\_/ \___|\__,_|_|\_\___/
#


# Pokrocile upravy Minecraftu
hack-minecraft:

  # Povoleni extra stakovani itemu, ktere normalne nejsou stakovat! Pozor: Muze bugovat!
  stacking:
    enabled: false # Pokud je na true, seznam dole pujde stakovat
    list:
      - 'WATER_BUCKET'
      - 'LAVA_BUCKET'

# Upravy chovani serveru (pokud je true) ochrana je aktivni
disables-and-fixes:

  # Deaktivace pouzivani nametagu na ArmorStandy
  nametag-on-armorstand: false

  # Deaktivace teleportu přes portály
  disable-portals: false

  # Deaktivace TNT exploze
  tnt-explosion: false

  # Deaktivace gravitace na armorstandu, aby nešel posunovat pomocí vody
  armorstand-gravity: false

  # Deaktivace níčení v určitém světě
  block-break:
    enabled: true
    worlds:
      - world

  # Deaktivace pokladani bloku v daném světě
  block-place:
    enabled: true
    world:
      - world

### CONSOLE HIDER ###
#
#    hide-message:
#    - 'WARNING: unlocalizedName'
#
# Skryje vsechny zprav v konzoli, ktere obsahuji zadany text.
console:
  hide-message:
    - 'Kek: warning'


# Limity bloků na chunk, podle https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
chunk-limiter:
  enabled: true
  entities:
    # Nazev musi odpovidat nazvu v MC
    MINECART: 10 # Limit 10 na chunk
    CHEST_MINECART: 10

# Omezování spawnu entit pomocí procentuální šance
entity-spawnrate:
  enabled: false
  default-spawnrate: 100 # 100% default spawnrate
  entities:
    # Nazev musi odpovidat nazvu v MC
    COW: 100 # 100% spawnrate
    CREEPER: 0 # Vypnutí spawningu
    SKELETON: 50 # 50% spawnrate

# Omezování celkovího počtu spawnu entit na serveru
# **Může způsobovat větší lagy kvůli výpočtům.**
entity-limiter:
  enabled: false
  max-entities: 1200 # Maximální počet entit na serveru
  use-tps: false # Zda se má spawn-rate kontrolovat dle TPS

# Příkazy, které se spustí po startu serveru
after-start:
  commands:
    - say Server has sucessfully started!


